from glob import glob
import matplotlib.pyplot as plt
import csv
import xlwt
print('Generated by ShaozhenLiu On Oct18')
paths = glob('./*.csv')
print('All the csv file path: ',paths)
for path in paths:
    para0 = []
    data =csv.reader(open(path,'r'))
    for i in data:
        para0.append(i[12])
    para = para0[3::]
    res_y =[]
    n = 1
    for i in para:
        try:
            r = float(i)
            if r <0:
                res_y.append(0)
            else:
                res_y.append(r)
        except:
            res_y.append(float(0))
    res_x = [i for i in range(1,len(res_y)+1)]
    res = []
    n_iter = len(res_x)
    sz = (n_iter,)
    z = res_y
    Q = 1e-5
    flag = input('Please choose initializtion of Q:')
    if flag =='3':
        Q = 1e-3
    if flag =='4':
        Q = 1e-4
    if flag == '5':
        Q =1e-5
    if flag =='6':
        Q =1e-6
    xhat = [0 for i in res_x]
    P = [0 for i in res_x]
    xhatminus = [0 for i in res_x]
    Pminus = [0 for i in res_x]
    K = [0 for i in res_x]
    R = 0.1 ** 2
    xhat[0] = res_y[0]
    P[0] = 1.0
    for k in range(1, n_iter):
        xhatminus[k] = xhat[k - 1]
        Pminus[k] = P[k - 1] + Q
        K[k] = Pminus[k] / (Pminus[k] + R)
        xhat[k] = xhatminus[k] + K[k] * (z[k] - xhatminus[k])
        P[k] = (1 - K[k]) * Pminus[k]
    plt.plot(res_x,res_y)
    plt.plot(res_x,xhat)
    plt.show()
    f = xlwt.Workbook()
    table = f.add_sheet(u'result', cell_overwrite_ok=True)
    colum = 0
    table.write(0, colum, 'Time/s')
    catg = para0[0]
    table.write(0, colum+1, str(catg) + '/ppm')
    ros = 1
    for i in range(len(res_x)):
        table.write(ros, colum, res_x[i])
        table.write(ros, colum+1, xhat[i])
        ros = ros+1
    fn = path.split('/')[0]+str('.xls')
    f.save(fn)
    print('The file has been saved as:',fn)
    print('Process has been completed !!')
    # input('Please click enter to close...')